#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
python3 "$SCRIPT_DIR/../py/dl-latest-rs.py" https://github.com/ChrisTorng/cli-tools/releases/download/v1.0/cli-tools "$SCRIPT_DIR/../rs/release/"
